In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("../data/raw/Online Retail.xlsx")

In [2]:
df.shape

(541909, 8)

In [3]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing.sort_values("Missing_Percentage", ascending=False)

             Missing_Count  Missing_Percentage
CustomerID          135080           24.926694
Description           1454            0.268311
StockCode                0            0.000000
InvoiceNo                0            0.000000
Quantity                 0            0.000000
InvoiceDate              0            0.000000
UnitPrice                0            0.000000
Country                  0            0.000000

In [6]:
df.duplicated().sum()

np.int64(5268)

In [7]:
df[df.duplicated()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [8]:
df = df.drop_duplicates()

In [9]:
df.shape

(536641, 8)

In [10]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9251)

In [11]:
df[df["InvoiceNo"].astype(str).str.startswith("C")].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [12]:
df = df[
    ~df["InvoiceNo"].astype(str).str.startswith("C")
].copy()

In [13]:
df.shape

(527390, 8)

In [14]:
df["Quantity"].describe()

count    527390.000000
mean         10.311272
std         160.367285
min       -9600.000000
25%           1.000000
50%           3.000000
75%          11.000000
max       80995.000000
Name: Quantity, dtype: float64

In [15]:
df["Quantity"].min()

np.int64(-9600)

In [16]:
df[df["Quantity"] <= 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom

In [17]:
df = df[df["Quantity"] > 0].copy()

In [18]:
df["Quantity"].min()

np.int64(1)

In [19]:
df["UnitPrice"].describe()

count    526054.000000
mean          3.871747
std          42.016560
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       13541.330000
Name: UnitPrice, dtype: float64

In [20]:
df[df["UnitPrice"] <= 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [21]:
df = df[df["UnitPrice"] > 0].copy()

In [22]:
df["Description"].isnull().sum()

np.int64(0)

In [23]:
df[df["Description"].isnull()][
    ["StockCode", "Quantity", "InvoiceNo"]
].head()

Empty DataFrame
Columns: [StockCode, Quantity, InvoiceNo]
Index: []

In [24]:
df["CustomerID"].isnull().sum()

np.int64(132186)

In [25]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [26]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [27]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [28]:
df["StockCode"].nunique()

3922

In [29]:
df["StockCode"].value_counts().head(10)

StockCode
85123A    2253
85099B    2109
22423     2007
47566     1699
20725     1582
84879     1476
22197     1418
22720     1392
21212     1352
22383     1306
Name: count, dtype: int64

In [30]:
df["InvoiceNo"].nunique()

19960

In [31]:
df["StockCode"].value_counts().tail(20)

StockCode
90020     1
84201C    1
90060B    1
84773     1
35610B    1
90126A    1
47591b    1
84971l    1
85049c    1
72802c    1
23609     1
85179a    1
84550     1
90214U    1
79323P    1
23617     1
90162A    1
23843     1
84854     1
90069     1
Name: count, dtype: int64

In [32]:
print("Rows:", len(df))
print("Orders:", df["InvoiceNo"].nunique())
print("Products:", df["StockCode"].nunique())
print("Customers:", df["CustomerID"].nunique())

Rows: 524878
Orders: 19960
Products: 3922
Customers: 4338

In [33]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132186
Country             0
dtype: int64

In [34]:
df.to_csv(
    "../data/processed/cleaned_online_retail.csv",
    index=False
)