In [21]:
product_features = pd.read_csv(
    "../data/processed/product_clusters_v2.csv",
    index_col=0
)

product_features.index.name = "StockCode"
product_features.head()

,total_quantity,avg_quantity_per_order,related_product_count,cluster,cluster_name
StockCode,,,,,
71,860,12.112676,2067,2,High-Volume Products
22,303,13.772727,908,0,Active/Regular Products
29,192,6.620690,1001,0,Active/Regular Products
3,5,1.666667,85,1,Slow-Moving Products
5,16,3.200000,196,1,Slow-Moving Products

In [22]:
zone_mapping = {
    "High-Volume Products": "Zone A",
    "Active/Regular Products": "Zone B",
    "Low-Movement Products": "Zone C",
    "Slow-Moving Products": "Zone D"
}

In [23]:
product_features["recommended_zone"] = (
    product_features["cluster_name"].map(zone_mapping)
)

In [24]:
product_features = product_features.reset_index()

product_features[
    ["StockCode", "cluster_name", "recommended_zone"]
].head(20)

    StockCode             cluster_name recommended_zone
0          71     High-Volume Products           Zone A
1          22  Active/Regular Products           Zone B
2          29  Active/Regular Products           Zone B
3           3     Slow-Moving Products           Zone D
4           5     Slow-Moving Products           Zone D
5           4     Slow-Moving Products           Zone D
6          91     High-Volume Products           Zone A
7         196     High-Volume Products           Zone A
8         175     High-Volume Products           Zone A
9         113     High-Volume Products           Zone A
10         12    Low-Movement Products           Zone C
11        138     High-Volume Products           Zone A
12        518     High-Volume Products           Zone A
13        145     High-Volume Products           Zone A
14        102  Active/Regular Products           Zone B
15         60  Active/Regular Products           Zone B
16         88  Active/Regular Products           Zone B
17         84  Active/Regular Products           Zone B
18        321     High-Volume Products           Zone A
19        456     High-Volume Products           Zone A

In [25]:
product_features["slot_number"] = (
    product_features.groupby("recommended_zone").cumcount() + 1
)

In [26]:
product_features["recommended_slot"] = (
    product_features["recommended_zone"]
    + "-"
    + product_features["slot_number"].astype(str)
)

In [27]:
product_features.head(20)

,StockCode,total_quantity,avg_quantity_per_order,related_product_count,cluster,cluster_name,recommended_zone,slot_number,recommended_slot
0,71,860,12.112676,2067,2,High-Volume Products,Zone A,1,Zone A-1
1,22,303,13.772727,908,0,Active/Regular Products,Zone B,1,Zone B-1
2,29,192,6.620690,1001,0,Active/Regular Products,Zone B,2,Zone B-2
3,3,5,1.666667,85,1,Slow-Moving Products,Zone D,1,Zone D-1
4,5,16,3.200000,196,1,Slow-Moving Products,Zone D,2,Zone D-2
5,4,17,4.250000,199,1,Slow-Moving Products,Zone D,3,Zone D-3
6,91,1295,14.230769,2373,2,High-Volume Products,Zone A,2,Zone A-2
7,196,2856,14.571429,2732,2,High-Volume Products,Zone A,3,Zone A-3
8,175,2229,12.737143,2893,2,High-Volume Products,Zone A,4,Zone A-4
9,113,1615,14.292035,2803,2,High-Volume Products,Zone A,5,Zone A-5
10,12,143,11.916667,465,3,Low-Movement Products,Zone C,1,Zone C-1
11,138,6591,47.760870,2868,2,High-Volume Products,Zone A,6,Zone A-6
12,518,23826,45.996139,3267,2,High-Volume Products,Zone A,7,Zone A-7
13,145,2090,14.413793,2953,2,High-Volume Products,Zone A,8,Zone A-8
14,102,458,4.490196,2355,0,Active/Regular Products,Zone B,3,Zone B-3
15,60,321,5.350000,1739,0,Active/Regular Products,Zone B,4,Zone B-4
16,88,313,3.556818,2369,0,Active/Regular Products,Zone B,5,Zone B-5
17,84,644,7.666667,2108,0,Active/Regular Products,Zone B,6,Zone B-6
18,321,2844,8.859813,2929,2,High-Volume Products,Zone A,9,Zone A-9
19,456,3950,8.662281,3161,2,High-Volume Products,Zone A,10,Zone A-10

In [28]:
product_features.to_csv(
    "../data/processed/final_slot_recommendations.csv",
    index=False
)