In [33]:
import pandas as pd

product_features = pd.read_csv(
    "../data/processed/product_clusters_v2.csv",
    index_col=0
)

product_features.index.name = "StockCode"
product_features = product_features.reset_index()
product_features.head()

,StockCode,total_quantity,avg_quantity_per_order,related_product_count,cluster,cluster_name
0,71,860,12.112676,2067,2,High-Volume Products
1,22,303,13.772727,908,0,Active/Regular Products
2,29,192,6.620690,1001,0,Active/Regular Products
3,3,5,1.666667,85,1,Slow-Moving Products
4,5,16,3.200000,196,1,Slow-Moving Products

In [34]:
zone_mapping = {
    "High-Volume Products": "Zone A",
    "Active/Regular Products": "Zone B",
    "Low-Movement Products": "Zone C",
    "Slow-Moving Products": "Zone D"
}

In [35]:
product_features["recommended_zone"] = (
    product_features["cluster_name"].map(zone_mapping)
)

In [36]:
product_features[
    ["StockCode", "cluster_name", "recommended_zone"]
].head(20)

    StockCode             cluster_name recommended_zone
0          71     High-Volume Products           Zone A
1          22  Active/Regular Products           Zone B
2          29  Active/Regular Products           Zone B
3           3     Slow-Moving Products           Zone D
4           5     Slow-Moving Products           Zone D
5           4     Slow-Moving Products           Zone D
6          91     High-Volume Products           Zone A
7         196     High-Volume Products           Zone A
8         175     High-Volume Products           Zone A
9         113     High-Volume Products           Zone A
10         12    Low-Movement Products           Zone C
11        138     High-Volume Products           Zone A
12        518     High-Volume Products           Zone A
13        145     High-Volume Products           Zone A
14        102  Active/Regular Products           Zone B
15         60  Active/Regular Products           Zone B
16         88  Active/Regular Products           Zone B
17         84  Active/Regular Products           Zone B
18        321     High-Volume Products           Zone A
19        456     High-Volume Products           Zone A

In [37]:
zone_distance = {
    "Zone A": 10,
    "Zone B": 25,
    "Zone C": 40,
    "Zone D": 60
}

In [38]:
product_features["distance_from_packing"] = (
    product_features["recommended_zone"].map(zone_distance)
)

In [39]:
product_features[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone",
        "distance_from_packing"
    ]
].head(20)

    StockCode             cluster_name recommended_zone  distance_from_packing
0          71     High-Volume Products           Zone A                     10
1          22  Active/Regular Products           Zone B                     25
2          29  Active/Regular Products           Zone B                     25
3           3     Slow-Moving Products           Zone D                     60
4           5     Slow-Moving Products           Zone D                     60
5           4     Slow-Moving Products           Zone D                     60
6          91     High-Volume Products           Zone A                     10
7         196     High-Volume Products           Zone A                     10
8         175     High-Volume Products           Zone A                     10
9         113     High-Volume Products           Zone A                     10
10         12    Low-Movement Products           Zone C                     40
11        138     High-Volume Products           Zone A                     10
12        518     High-Volume Products           Zone A                     10
13        145     High-Volume Products           Zone A                     10
14        102  Active/Regular Products           Zone B                     25
15         60  Active/Regular Products           Zone B                     25
16         88  Active/Regular Products           Zone B                     25
17         84  Active/Regular Products           Zone B                     25
18        321     High-Volume Products           Zone A                     10
19        456     High-Volume Products           Zone A                     10

In [56]:
df = pd.read_csv(
    "../data/processed/cleaned_online_retail.csv"
)
df["StockCode"] = df["StockCode"].astype(str)
product_features["StockCode"] = product_features["StockCode"].astype(str)

C:\Users\HP\AppData\Local\Temp\ipykernel_40140\1697342282.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [57]:
order_frequency = (
    df.groupby("StockCode")["InvoiceNo"]
      .nunique()
      .rename("order_frequency")
)

In [58]:
order_frequency.head()

StockCode
10002     71
10080     22
10120     29
10123C     3
10124A     5
Name: order_frequency, dtype: int64

In [59]:
product_features = product_features.merge(
    order_frequency,
    on="StockCode",
    how="left"
)

In [60]:
print(product_features.columns.tolist())

['StockCode', 'total_quantity', 'avg_quantity_per_order', 'related_product_count', 'cluster', 'cluster_name', 'recommended_zone', 'distance_from_packing', 'order_frequency']

In [61]:
product_features["order_frequency"].isna().sum()

np.int64(3922)

In [62]:
product_features["order_frequency"] = (
    product_features["order_frequency"].fillna(0)
)

In [63]:
product_features["picking_priority"] = (
    product_features["order_frequency"] *
    product_features["total_quantity"]
)

In [64]:
top_products = product_features.sort_values(
    "picking_priority",
    ascending=False
)

top_products[
    [
        "StockCode",
        "order_frequency",
        "total_quantity",
        "cluster_name",
        "recommended_zone",
        "picking_priority"
    ]
].head(10)

,StockCode,order_frequency,total_quantity,cluster_name,recommended_zone,picking_priority
0,71,0.0,860,High-Volume Products,Zone A,0.0
1,22,0.0,303,Active/Regular Products,Zone B,0.0
2,29,0.0,192,Active/Regular Products,Zone B,0.0
3,3,0.0,5,Slow-Moving Products,Zone D,0.0
4,5,0.0,16,Slow-Moving Products,Zone D,0.0
5,4,0.0,17,Slow-Moving Products,Zone D,0.0
6,91,0.0,1295,High-Volume Products,Zone A,0.0
7,196,0.0,2856,High-Volume Products,Zone A,0.0
8,175,0.0,2229,High-Volume Products,Zone A,0.0
9,113,0.0,1615,High-Volume Products,Zone A,0.0

In [65]:
product_features["current_distance"] = 60

In [66]:
product_features["distance_saved"] = (
    product_features["current_distance"]
    - product_features["distance_from_packing"]
)

In [67]:
product_features[
    [
        "StockCode",
        "current_distance",
        "distance_from_packing",
        "distance_saved"
    ]
].head(20)

   StockCode  current_distance  distance_from_packing  distance_saved
0         71                60                     10              50
1         22                60                     25              35
2         29                60                     25              35
3          3                60                     60               0
4          5                60                     60               0
5          4                60                     60               0
6         91                60                     10              50
7        196                60                     10              50
8        175                60                     10              50
9        113                60                     10              50
10        12                60                     40              20
11       138                60                     10              50
12       518                60                     10              50
13       145                60                     10              50
14       102                60                     25              35
15        60                60                     25              35
16        88                60                     25              35
17        84                60                     25              35
18       321                60                     10              50
19       456                60                     10              50

In [68]:
total_current_distance = (
    product_features["current_distance"]
    * product_features["order_frequency"]
).sum()

In [69]:
total_recommended_distance = (
    product_features["distance_from_packing"]
    * product_features["order_frequency"]
).sum()

In [70]:
travel_reduction = (
    (total_current_distance - total_recommended_distance)
    / total_current_distance
) * 100

C:\Users\HP\AppData\Local\Temp\ipykernel_40140\928008467.py:2: RuntimeWarning: invalid value encountered in scalar divide
  (total_current_distance - total_recommended_distance)

In [71]:
print(
    f"Estimated travel reduction: {travel_reduction:.2f}%"
)

Estimated travel reduction: nan%

In [72]:
product_features[
    [
        "order_frequency",
        "current_distance",
        "distance_from_packing"
    ]
].isna().sum()

order_frequency          0
current_distance         0
distance_from_packing    0
dtype: int64

In [73]:
print("Current distance:", total_current_distance)
print("Recommended distance:", total_recommended_distance)
print("Travel reduction:", travel_reduction)

Current distance: 0.0
Recommended distance: 0.0
Travel reduction: nan

In [74]:
print(
    product_features[
        [
            "order_frequency",
            "current_distance",
            "distance_from_packing"
        ]
    ].dtypes
)

order_frequency          float64
current_distance           int64
distance_from_packing      int64
dtype: object

In [75]:
product_features["order_frequency"] = pd.to_numeric(
    product_features["order_frequency"],
    errors="coerce"
)

product_features["current_distance"] = pd.to_numeric(
    product_features["current_distance"],
    errors="coerce"
)

product_features["distance_from_packing"] = pd.to_numeric(
    product_features["distance_from_packing"],
    errors="coerce"
)

In [76]:
print(
    product_features[
        [
            "order_frequency",
            "current_distance",
            "distance_from_packing"
        ]
    ].isna().sum()
)

order_frequency          0
current_distance         0
distance_from_packing    0
dtype: int64

In [77]:
total_current_distance = (
    product_features["current_distance"]
    * product_features["order_frequency"]
).sum()

total_recommended_distance = (
    product_features["distance_from_packing"]
    * product_features["order_frequency"]
).sum()

print("Current:", total_current_distance)
print("Recommended:", total_recommended_distance)

Current: 0.0
Recommended: 0.0

In [78]:
travel_reduction = (
    (total_current_distance - total_recommended_distance)
    / total_current_distance
) * 100

print(f"Estimated travel reduction: {travel_reduction:.2f}%")

Estimated travel reduction: nan%

C:\Users\HP\AppData\Local\Temp\ipykernel_40140\1085259812.py:2: RuntimeWarning: invalid value encountered in scalar divide
  (total_current_distance - total_recommended_distance)

In [79]:
print("Current:", total_current_distance)
print("Recommended:", total_recommended_distance)
print(product_features[
    ["order_frequency", "current_distance", "distance_from_packing"]
].dtypes)

Current: 0.0
Recommended: 0.0
order_frequency          float64
current_distance           int64
distance_from_packing      int64
dtype: object

In [80]:
df["StockCode"] = (
    df["StockCode"]
    .astype(str)
    .str.strip()
)

product_features["StockCode"] = (
    product_features["StockCode"]
    .astype(str)
    .str.strip()
)

In [81]:
order_frequency = (
    df.groupby("StockCode")["InvoiceNo"]
      .nunique()
      .reset_index(name="order_frequency")
)

In [82]:
print(order_frequency.head())
print(order_frequency["order_frequency"].describe())

  StockCode  order_frequency
0     10002               71
1     10080               22
2     10120               29
3    10123C                3
4    10124A                5
count    3922.000000
mean      132.484192
std       193.890513
min         1.000000
25%        16.000000
50%        65.000000
75%       165.000000
max      2198.000000
Name: order_frequency, dtype: float64

In [83]:
if "order_frequency" in product_features.columns:
    product_features = product_features.drop(
        columns=["order_frequency"]
    )

In [84]:
product_features = product_features.merge(
    order_frequency,
    on="StockCode",
    how="left"
)

In [85]:
print(product_features["order_frequency"].describe())

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: order_frequency, dtype: float64

In [86]:
print(
    product_features[
        ["StockCode", "order_frequency"]
    ].head(20)
)

   StockCode  order_frequency
0         71              NaN
1         22              NaN
2         29              NaN
3          3              NaN
4          5              NaN
5          4              NaN
6         91              NaN
7        196              NaN
8        175              NaN
9        113              NaN
10        12              NaN
11       138              NaN
12       518              NaN
13       145              NaN
14       102              NaN
15        60              NaN
16        88              NaN
17        84              NaN
18       321              NaN
19       456              NaN

In [87]:
print(product_features.head())

  StockCode  total_quantity  avg_quantity_per_order  related_product_count  \
0        71             860               12.112676                   2067
1        22             303               13.772727                    908
2        29             192                6.620690                   1001
3         3               5                1.666667                     85
4         5              16                3.200000                    196

   cluster             cluster_name recommended_zone  distance_from_packing  \
0        2     High-Volume Products           Zone A                     10
1        0  Active/Regular Products           Zone B                     25
2        0  Active/Regular Products           Zone B                     25
3        1     Slow-Moving Products           Zone D                     60
4        1     Slow-Moving Products           Zone D                     60

   picking_priority  current_distance  distance_saved  order_frequency
0               0.0                60              50              NaN
1               0.0                60              35              NaN
2               0.0                60              35              NaN
3               0.0                60               0              NaN
4               0.0                60               0              NaN

In [88]:
print(product_features.index[:20])

RangeIndex(start=0, stop=20, step=1)

In [89]:
print(df[["StockCode", "InvoiceNo"]].head(20))

   StockCode InvoiceNo
0     85123A    536365
1      71053    536365
2     84406B    536365
3     84029G    536365
4     84029E    536365
5      22752    536365
6      21730    536365
7      22633    536366
8      22632    536366
9      84879    536367
10     22745    536367
11     22748    536367
12     22749    536367
13     22310    536367
14     84969    536367
15     22623    536367
16     22622    536367
17     21754    536367
18     21755    536367
19     21777    536367

In [90]:
print(product_features.shape)

(3922, 12)

In [91]:
print(product_features["StockCode"].head(20).tolist())

['71', '22', '29', '3', '5', '4', '91', '196', '175', '113', '12', '138', '518', '145', '102', '60', '88', '84', '321', '456']

In [92]:
product_base = df.groupby("StockCode").agg(
    total_quantity=("Quantity", "sum"),
    avg_quantity_per_order=("Quantity", "mean")
).reset_index()

In [93]:
product_base.head()

  StockCode  total_quantity  avg_quantity_per_order
0     10002             860               12.112676
1     10080             303               13.772727
2     10120             192                6.620690
3    10123C               5                1.666667
4    10124A              16                3.200000

In [94]:
order_frequency = (
    df.groupby("StockCode")["InvoiceNo"]
      .nunique()
      .reset_index(name="order_frequency")
)

In [95]:
product_base = product_base.merge(
    order_frequency,
    on="StockCode",
    how="left"
)

In [96]:
product_base.head()

  StockCode  total_quantity  avg_quantity_per_order  order_frequency
0     10002             860               12.112676               71
1     10080             303               13.772727               22
2     10120             192                6.620690               29
3    10123C               5                1.666667                3
4    10124A              16                3.200000                5

In [98]:
pairs_df = pd.read_csv(
    "../data/processed/product_pairs.csv"
)

In [99]:
print(pairs_df.head())
print(pairs_df.columns)

          Product_Pair  Order_Count   support
0  ('22386', '85099B')          825  0.041329
1   ('22697', '22699')          767  0.038423
2  ('21931', '85099B')          724  0.036269
3  ('22411', '85099B')          680  0.034065
4   ('20725', '22383')          655  0.032812
Index(['Product_Pair', 'Order_Count', 'support'], dtype='object')

In [100]:
import ast

related_products = {}

for pair in pairs_df["Product_Pair"]:
    try:
        product_a, product_b = ast.literal_eval(pair)

        product_a = str(product_a).strip()
        product_b = str(product_b).strip()

        related_products.setdefault(product_a, set()).add(product_b)
        related_products.setdefault(product_b, set()).add(product_a)

    except:
        pass

In [101]:
print(len(related_products))

3913

In [102]:
list(related_products.items())[:5]

[('22386',
  {'22156',
   '22352',
   '22581',
   '90039B',
   '23638',
   '85049F',
   '22431',
   '22090',
   '23004',
   '23335',
   '22561',
   '22959',
   '23009',
   '23281',
   '21792',
   '22631',
   '23156',
   '20622',
   '22766',
   '21061',
   '90040C',
   '22073',
   '21742',
   '21992',
   '72807c',
   '22149',
   '22271',
   '82613D',
   '22121',
   '22359',
   '22128',
   '22881',
   '21188',
   '85017A',
   '84944',
   '35818P',
   '23530',
   '84659A',
   '22311',
   '22857',
   '84251B',
   '21747',
   '21576',
   '23218',
   '22861',
   '21367',
   '90200C',
   '23598',
   '85126',
   '22815',
   '22846',
   '22110',
   '21332',
   '35650',
   '21181',
   '21390',
   '20782',
   '22935',
   '22873',
   '35967',
   '23178',
   '85205B',
   '22395',
   '21028',
   '22818',
   '22350',
   '22024',
   '22255',
   '90063B',
   '23043',
   '21243',
   '21678',
   '85132B',
   '84508A',
   '22883',
   '16048',
   '22523',
   '21866',
   '90055',
   '85132a',
   '22972',
   '22509',
   '82552',
   '22970',
   '90214Z',
   '23479',
   '84997a',
   '21822',
   '21563',
   '22371',
   '23052',
   '23608',
   '71270',
   '21003',
   '22620',
   '22406',
   '90180A',
   '23124',
   '90144',
   '85130D',
   '90029',
   '21722',
   '22429',
   '15056P',
   '22180',
   '22742',
   '23377',
   '23319',
   '23129',
   '22510',
   '22432',
   '35961',
   '22622',
   '21415',
   'DCGS0004',
   '90177D',
   '51014L',
   '22643',
   '23321',
   '90214C',
   '46776A',
   '47585A',
   '23018',
   '51014c',
   '22326',
   '23517',
   '90210D',
   '22675',
   '23406',
   '21211',
   '21676',
   '22753',
   '22335',
   '22928',
   '23271',
   '90059F',
   '21695',
   '23280',
   '22076',
   '90079',
   '22856',
   '22196',
   '22775',
   '85008',
   '23123',
   '23314',
   '84754',
   '84711B',
   '22681',
   '84249A',
   '22500',
   '22686',
   '16225',
   '21850',
   '23399',
   '23153',
   '47580',
   '84987',
   '23513',
   '22553',
   '72802B',
   '22504',
   '35651',
   '90129F',
   '22381',
   '85163A',
   '23478',
   '21263',
   '23467',
   '72349b',
   '22328',
   '23157',
   '35957',
   '21222',
   '90128A',
   '90000A',
   '82494L',
   '20750',
   '21972',
   '21662',
   '85036B',
   '71495B',
   '84658',
   '23310',
   '23208',
   '22651',
   '23374',
   '22106',
   '22115',
   '23050',
   '22886',
   '22112',
   '21905',
   '21051',
   '16052',
   '37482P',
   '22481',
   '90141C',
   '85179a',
   '22304',
   '23025',
   '22283',
   '21973',
   '21318',
   '21429',
   '22606',
   '20898',
   '84898F',
   '85124C',
   '79403',
   '84968a',
   '23060',
   '22844',
   '23533',
   '22576',
   '47599A',
   '21547',
   '22797',
   '82613B',
   '22447',
   '22653',
   '47594A',
   '84926F',
   '22689',
   '22428',
   '22990',
   '84924A',
   '90192',
   '23191',
   '23112',
   '90160D',
   '23546',
   '75049L',
   '23034',
   '85231b',
   '21292',
   '21206',
   '16259',
   '21356',
   '21819',
   '23421',
   '21156',
   '23110',
   '23007',
   '23046',
   '17091J',
   '21509',
   '90119',
   '85024C',
   '47566b',
   '85059',
   '72130',
   '90161D',
   '22820',
   '22194',
   '72807a',
   '22814',
   '21446',
   '47586A',
   '17012D',
   '22764',
   '21078',
   '20766',
   '22843',
   '21251',
   '22458',
   '90030B',
   '84247L',
   'M',
   '22907',
   '21494',
   '22470',
   '22862',
   '37450',
   '20701',
   '22111',
   '21062',
   '23301',
   '23236',
   '21618',
   '90125C',
   '21826',
   '22439',
   '35004B',
   '22474',
   '22085',
   '21226',
   '21717',
   '22718',
   '22488',
   '22964',
   '21713',
   '21823',
   '22596',
   '21672',
   '22216',
   '22515',
   '23454',
   '23681',
   '84968C',
   '23380',
   '85035A',
   '84968A',
   '21498',
   '90214V',
   '35916A',
   '23369',
   '23358',
   '84763',
   '21286',
   '84857C',
   '23026',
   '23558',
   '90027B',
   '22784',
   '23239',
   '84970S',
   '23273',
   '21626',
   '22619',
   '85208',
   '23428',
   '84688',
   '23695',
   '22153',
   '21199',
   '23002',
   '22320',
   '90214D',
   '23065',
   '22702',
   '22669',
   '21136',
   '22379',
   '22798',
   '90011A',
   '84813',
   '22249',
   '48173C',
   '84970L',
   '84660C',
   '23633',
   '84032B',
   '23502',
   '90186A',
   '23489',
   '90199D',
   '23463',
   '22771',
   '47369A',
   '23177',
   '21556',
   '22826',
   '84406B',
   '23570',
   '85078',
   '20770',
   '85018D',
   '22618',
   '90013A',
   '84031B',
   '22294',
   '46776f',
   '23318',
   '22947',
   '22565',
   '84030E',
   '23092',
   '20652',
   '23228',
   '23263',
   '22130',
   '84849B',
   '84968D',
   '16238',
   '22682',
   '22284',
   '85014b',
   '22093',
   '90037B',
   '90206C',
   '21949',
   '84880',
   '22446',
   '21873',
   '84881',
   '84870C',
   '23128',
   '23523',
   '85103',
   '22062',
   '22556',
   '23646',
   '21422',
   '22809',
   '84748',
   '37475',
   '85025C',
   '84916',
   '23565',
   '23621',
   '85014B',
   '20971',
   '16169M',
   '21895',
   '22148',
   '85034a',
   '21056',
   '22087',
   '21912',
   '21531',
   '85036C',
   '20654',
   '85213',
   '15058A',
   '90147',
   '23610',
   '21413',
   '84968F',
   '21084',
   '20932',
   '23578',
   '35911A',
   '21932',
   '23607',
   '37342',
   '47422',
   'gift_0001_30',
   '21359',
   '22498',
   '85053',
   '21801',
   '84581',
   '23216',
   '21167',
   '15056bl',
   '84725',
   '22162',
   '85040A',
   '22642',
   '22719',
   '22992',
   '21218',
   '37448',
   '21746',
   '23144',
   '84872a',
   '22634',
   '22408',
   '22448',
   '23351',
   '84510c',
   '23538',
   '21135',
   '22918',
   '23068',
   '23222',
   '23475',
   '82613b',
   '22212',
   '20846',
   '72802C',
   '90214L',
   '23324',
   '84251C',
   '22879',
   '23540',
   '22664',
   '22220',
   '17038',
   '82001s',
   '21520',
   '21033',
   '22071',
   '90040A',
   '72819',
   '84796B',
   '22299',
   '21209',
   '37462E',
   '22227',
   '22703',
   '23249',
   '21204',
   '85087',
   '21106',
   '84707B',
   '21246',
   '90092',
   '22800',
   '21918',
   '23444',
   '90201D',
   '22035',
   '22750',
   '21336',
   '22965',
   '90211B',
   '62096B',
   '90063A',
   '79067',
   '21248',
   '20754',
   '20675',
   '15056BL',
   '90214I',
   '47367B',
   '90059B',
   '22603',
   '21704',
   '47599B',
   '16218',
   '23080',
   '23111',
   '22365',
   '22168',
   '90158',
   '21095',
   '22629',
   '90014A',
   '22315',
   '23654',
   '22697',
   '71459',
   '21026',
   '84596g',
   '84926E',
   '23070',
   '23405',
   '22507',
   '82580',
   '22923',
   '85116',
   '90081A',
   '23378',
   '84559A',
   '22422',
   '23186',
   '18094C',
   '22308',
   '21132',
   '21294',
   '22746',
   '85189',
   '22739',
   '22063',
   '21507',
   '22939',
   '22614',
   '21922',
   '85014a',
   '23162',
   '22208',
   '85230A',
   '20986',
   '90010E',
   '22183',
   '23552',
   '22164',
   '23165',
   '21398',
   '20725',
   '22261',
   '21389',
   '22666',
   '22607',
   '72760B',
   '23640',
   '23233',
   '21675',
   '84907',
   '85188A',
   '84970s',
   '37491A',
   '90124C',
   '22897',
   '21187',
   '23567',
   '23317',
   '22884',
   '23286',
   '85131C',
   '21738',
   '22517',
   '21364',
   '82613A',
   '21191',
   '22377',
   '90177E',
   '84638',
   '23451',
   '21457',
   '84993B',
   '22849',
   '22547',
   '22028',
   '85179A',
   '23272',
   '90114',
   '23512',
   '79406',
   '22029',
   '90125D',
   '22296',
   '22041',
   '22485',
   '23285',
   '22287',
   '85185D',
   '82484',
   '23151',
   '23639',
   '35809B',
   '21317',
   '78124',
   '22720',
   '23088',
   '85023B',
   '23549',
   '22579',
   '22732',
   '23501',
   '22197',
   '72811',
   '90012A',
   '82599',
   '22247',
   '21320',
   '23175',
   '21803',
   '22405',
   '85146',
   '85194S',
   '22414',
   '21648',
   '22616',
   '21524',
   '85035a',
   '90183c',
   '23117',
   '20769',
   '72802A',
   '23481',
   '90165A',
   '21002',
   '21975',
   '72128',
   '35004C',
   '22868',
   '21055',
   '21025',
   '84800L',
   '85186C',
   '21377',
   '72225C',
   '84231',
   '22601',
   '22440',
   '20969',
   '22360',
   '22494',
   '84755',
   '23376',
   '22288',
   '90184B',
   '22175',
   '21682',
   '22774',
   '22568',
   '40001',
   '79000',
   '22430',
   '21063',
   '85032B',
   '21715',
   '47574A',
   '72586',
   '20840',
   '21264',
   '21018',
   '23132',
   '22268',
   '23164',
   '90160C',
   '22841',
   '22303',
   '72598',
   '22088',
   '47503H',
   '85176',
   '15044C',
   '22133',
   '47591d',
   '23083',
   '23058',
   '35809A',
   '84509B',
   '84050',
   '90138',
   '22985',
   '21198',
   '90210B',
   '21592',
   '21794',
   '85169B',
   '20707',
   '85045',
   '90209C',
   '22878',
   '21670',
   '22605',
   '84527',
   '15056p',
   '20866',
   '84872A',
   '21379',
   '23021',
   '22519',
   '22802',
   '23432',
   '21830',
   '90028',
   '21116',
   '22813',
   '90163B',
   '79066K',
   '22877',
   '22107',
   '23256',
   '21875',
   '90122C',
   '21584',
   '22278',
   '23436',
   '23520',
   '21925',
   '21770',
   '20867',
   '20667',
   '22357',
   '85114c',
   '90018A',
   '84029E',
   '22625',
   '47504H',
   '84596J',
   '22053',
   '84809A',
   '21980',
   '90184C',
   '35607A',
   '22768',
   '85114B',
   '22265',
   '84875D',
   '21165',
   '23437',
   '21219',
   '22736',
   '90214P',
   '20653',
   '21872',
   '35810A',
   '22786',
   '23535',
   '84692',
   '23189',
   '82482',
   '15044A',
   '84422',
   '84993A',
   '21820',
   '21877',
   '22092',
   '90003B',
   '21059',
   '22838',
   '22078',
   '82613a',
   '22321',
   '35923',
   '90058B',
   '20670',
   '22835',
   '84341B',
   '47570b',
   '22187',
   '22496',
   '84818',
   '21989',
   '85152',
   '22781',
   '22150',
   '84949',
   '23507',
   '21192',
   '21756',
   '21402',
   '90214R',
   '85066',
   '21027',
   '23171',
   '85124B',
   '21845',
   '23196',
   '85199S',
   '47421',
   '84559b',
   '72800D',
   '22638',
   '35970',
   '84596f',
   '90186B',
   '22704',
   '90051',
   '23344',
   '90003C',
   '22922',
   '72741',
   '35095A',
   '21535',
   '22967',
   '22555',
   '84212',
   '84745B',
   '84997A',
   '90199C',
   '84706F',
   '90108',
   '85104',
   '84596E',
   '21851',
   '90059D',
   '84884A',
   '22974',
   '22957',
   '23244',
   '21486',
   '85119',
   '20682',
   '10002',
   '15044D',
   '85197',
   '90142A',
   '21306',
   '85168B',
   '21201',
   '84950',
   '23323',
   '23320',
   '90057',
   '22047',
   '22467',
   '21094',
   '20966',
   '23456',
   '35914',
   '84279P',
   '22280',
   '22345',
   '82011C',
   '79066k',
   '22829',
   '90169',
   '23288',
   '21623',
   '22419',
   '48129',
   '84746',
   '90156',
   '90214G',
   '22501',
   '90064A',
   '23579',
   '23302',
   '84558A',
   '22699',
   '22966',
   '21809',
   '21804',
   '85035C',
   '21200',
   '84497',
   '84247G',
   '23289',
   '23127',
   '22821',
   '22184',
   '90016B',
   '90077',
   '21705',
   '84798A',
   '21485',
   '82011B',
   '72812',
   '37444B',
   '85106',
   '22341',
   '85049D',
   '17012E',
   '84974',
   '22715',
   '22254',
   '23473',
   '21654',
   '90198B',
   '85114A',
   '20761',
   '21399',
   '22860',
   '21917',
   '23268',
   '21090',
   '23107',
   '20828',
   '46776F',
   '22973',
   '22066',
   '22394',
   '21707',
   '23429',
   '21277',
   '20764',
   '84661b',
   '22580',
   '22248',
   '72799E',
   '90123D',
   '90036C',
   '21175',
   '23031',
   '90099',
   '22310',
   '21948',
   '84913A',
   '22441',
   '21464',
   '81952V',
   '37500',
   '21810',
   '22042',
   '20661',
   '21944',
   '84856L',
   '22687',
   '21137',
   '35953',
   '23096',
   '85227',
   '90073',
   '84997B',
   '35599D',
   '79190B',
   '22228',
   '23556',
   '23067',
   '22127',
   '22080',
   '90089',
   '22649',
   '22476',
   '21383',
   '22307',
   '22550',
   '35933',
   '90038B',
   '22364',
   '85039B',
   '21619',
   '84563B',
   '22695',
   '22730',
   '22316',
   '23199',
   '20752',
   '15056n',
   '20674',
   '21465',
   '23003',
   '23315',
   '22874',
   '22505',
   '85173',
   '85049a',
   '90027C',
   '23139',
   '21633',
   '84915',
   '21215',
   '16020C',
   '23136',
   '84596B',
   '21462',
   '85036b',
   '84569B',
   '22587',
   '21488',
   '84199',
   '22613',
   '17084P',
   ...}),
 ('85099B',
  {'22156',
   '22352',
   '22581',
   '90039B',
   '23638',
   '85049F',
   '22431',
   '22090',
   '23004',
   '23335',
   '22561',
   '22959',
   '23009',
   '23281',
   '21792',
   '22631',
   '23156',
   '20622',
   '22766',
   '21061',
   '90040C',
   '22073',
   '21742',
   '21992',
   '72807c',
   '22149',
   '37479B',
   '22271',
   '82613D',
   '22121',
   '21420',
   '22359',
   '22128',
   '22881',
   '21188',
   '85017A',
   '84944',
   '35818P',
   '23530',
   '84659A',
   '22311',
   '22857',
   '84251B',
   '21747',
   '21576',
   '23218',
   '22861',
   '21367',
   '90200C',
   '23598',
   '85126',
   '22815',
   '22846',
   '22110',
   '21332',
   '35650',
   '21181',
   '21390',
   '20782',
   '22935',
   '22873',
   '35967',
   '23178',
   '90032',
   '85205B',
   '22395',
   '21028',
   '22818',
   '22350',
   '22024',
   '22255',
   '90063B',
   '23043',
   '21243',
   '21678',
   '85132B',
   '84508A',
   '22883',
   '16048',
   '22523',
   '21866',
   '90055',
   '85132a',
   '22972',
   '22509',
   '82552',
   '22970',
   '90214Z',
   '23479',
   '84997a',
   '21822',
   '21563',
   '22371',
   '23052',
   '23608',
   '71270',
   '21003',
   '22620',
   '22406',
   '90180A',
   '84051',
   '23124',
   '90144',
   '85130D',
   '90029',
   '90152A',
   '21722',
   '22429',
   '15056P',
   '22180',
   '22742',
   '23377',
   '23319',
   '23129',
   '22510',
   '22432',
   '35961',
   '22622',
   '21415',
   '23457',
   '90177D',
   '51014L',
   '22643',
   '23321',
   '90214C',
   '46776A',
   '47585A',
   '23018',
   '51014c',
   '22326',
   '23517',
   '90210D',
   '22675',
   '23406',
   '21676',
   '21211',
   '22753',
   '22335',
   '22928',
   '23271',
   '90059F',
   '21695',
   '23280',
   '22076',
   '22856',
   '90079',
   '90031',
   '22196',
   '22775',
   '85008',
   '23123',
   '23314',
   '84754',
   '22681',
   '84249A',
   '22500',
   '22686',
   '16225',
   '21850',
   '23399',
   '84731',
   '23153',
   '47580',
   '84987',
   '23513',
   '22553',
   '72802B',
   '22504',
   '35651',
   '90129F',
   '22381',
   '85163A',
   '23478',
   '23605',
   '21263',
   '23467',
   '72349b',
   '22328',
   '23157',
   '35957',
   '90036B',
   '21222',
   '90128A',
   '90000A',
   '82494L',
   '20750',
   '21972',
   '85036B',
   '21662',
   '71495B',
   '84658',
   '23310',
   '23208',
   '22651',
   '23374',
   '22106',
   '22115',
   '23050',
   '22886',
   '22112',
   '21905',
   '21051',
   '37482P',
   '16052',
   '22481',
   '90141C',
   '85179a',
   '22304',
   '23025',
   '22283',
   '21973',
   '22783',
   '20898',
   '21429',
   '22606',
   '21318',
   '84898F',
   '46000U',
   '85124C',
   '79403',
   '84968a',
   '23060',
   '22844',
   '23533',
   '22576',
   '47599A',
   '21547',
   '22797',
   '82613B',
   '22447',
   '22653',
   '22705',
   '47594A',
   '84926F',
   '22689',
   '90180B',
   '22428',
   '22990',
   '84924A',
   '90192',
   '23191',
   '84847',
   '23112',
   '90160D',
   '23546',
   '90082B',
   '75049L',
   '23034',
   '85231b',
   '21292',
   '21206',
   '16259',
   '21356',
   '21819',
   '23421',
   '21156',
   '23007',
   '23110',
   '85024C',
   '17091J',
   '21509',
   '90119',
   '23046',
   '23410',
   '47566b',
   '85059',
   '72130',
   '90161D',
   '22820',
   '22194',
   '72807a',
   '22814',
   '21446',
   '47586A',
   '17012D',
   '22764',
   '21078',
   '20766',
   '22843',
   '21251',
   '22458',
   '90030B',
   '84247L',
   'M',
   '22907',
   '21494',
   '22470',
   '22862',
   '37450',
   '20701',
   '22111',
   '90162C',
   '21062',
   '23301',
   '23236',
   '21618',
   '90125C',
   '21826',
   '90024E',
   '22439',
   '35004B',
   '22474',
   '22085',
   '21226',
   '21717',
   '22718',
   '22488',
   '22964',
   '21713',
   '21823',
   '22596',
   '72131',
   '21672',
   '22216',
   '22515',
   '23454',
   '23681',
   '84968C',
   '23380',
   '20835',
   '85035A',
   '84968A',
   '21498',
   'DCGS0069',
   '90214V',
   '35916A',
   '23369',
   '23358',
   '84763',
   '21286',
   '84857C',
   '23026',
   '23558',
   '90027B',
   '37489D',
   '22784',
   '23239',
   '84970S',
   '23273',
   '21626',
   '22619',
   '85208',
   '23428',
   '84688',
   '35810B',
   '23695',
   '22153',
   '21199',
   '23002',
   '22320',
   '90214D',
   '23065',
   '22702',
   '22669',
   '21136',
   '22379',
   '22798',
   '90011A',
   '84813',
   '22249',
   '48173C',
   '84970L',
   '84660C',
   '23633',
   '84032B',
   '23502',
   '90186A',
   '23489',
   '90199D',
   '23463',
   '22771',
   '47369A',
   '23177',
   '21556',
   '22826',
   '84406B',
   '84989A',
   '23570',
   '85078',
   '20770',
   '85018D',
   '22618',
   '90013A',
   '35922',
   '84031B',
   '22294',
   '46776f',
   '23318',
   '22947',
   '22565',
   '84030E',
   '23092',
   '23228',
   '20652',
   '23263',
   '22130',
   '84968D',
   '84849B',
   '16238',
   '22682',
   '22284',
   '22093',
   '85014b',
   '84549',
   '90037B',
   '90206C',
   '21949',
   '84880',
   '22446',
   '21873',
   '84881',
   '84870C',
   '23128',
   '23523',
   '85103',
   'gift_0001_50',
   '22062',
   '22556',
   '23646',
   '21422',
   '22809',
   '84748',
   '37475',
   '85025C',
   '44235',
   '84916',
   '23565',
   '23621',
   '85014B',
   '20971',
   '16169M',
   '21895',
   '22148',
   '85034a',
   '21056',
   '22087',
   '21912',
   '21531',
   '85036C',
   '20654',
   '85213',
   '15058A',
   '90147',
   '23610',
   '21413',
   '84968F',
   '21084',
   '20932',
   '23578',
   '35911A',
   '21932',
   '23607',
   '37342',
   '47422',
   'gift_0001_30',
   '21359',
   '22498',
   '85053',
   '21801',
   '84581',
   '23216',
   '21167',
   '15056bl',
   '84725',
   '22162',
   '90157',
   '85040A',
   '22642',
   '22719',
   '22992',
   '21218',
   '37448',
   '21746',
   '23448',
   '23144',
   '22634',
   '84872a',
   '22408',
   '22448',
   '23351',
   '84510c',
   '23538',
   '21135',
   '22918',
   '23068',
   '23222',
   '23475',
   '82613b',
   '22212',
   '20846',
   '72802C',
   '90214L',
   '23324',
   '84251C',
   '22879',
   '23540',
   '22664',
   '22220',
   '17038',
   '82001s',
   '21520',
   '21033',
   '22071',
   '90040A',
   '72819',
   '84796B',
   '22299',
   '21209',
   '37462E',
   '22227',
   '22703',
   '23249',
   '21204',
   '85087',
   '21106',
   '84707B',
   '21246',
   '90092',
   '22800',
   '21918',
   '23444',
   '90201D',
   '22035',
   '22750',
   '21336',
   '22965',
   '90211B',
   '62096B',
   '90063A',
   '79067',
   '21248',
   '20754',
   '20675',
   '15056BL',
   '90214I',
   '47367B',
   '90059B',
   '22603',
   '21704',
   '47599B',
   '16218',
   '23080',
   '23111',
   '22365',
   '22168',
   '90158',
   '21095',
   '17174',
   '22629',
   '90014A',
   '22315',
   '23654',
   '22697',
   '71459',
   '21026',
   '84926E',
   '84596g',
   '23405',
   '23070',
   '22507',
   '82580',
   '90210A',
   '22923',
   '85116',
   '90081A',
   '23378',
   '90179B',
   '84559A',
   '22422',
   '23186',
   '18094C',
   '22308',
   '21132',
   '21294',
   '22746',
   '22739',
   '22063',
   '21507',
   '22939',
   '22614',
   '21922',
   '85014a',
   '23162',
   '22208',
   '20986',
   '90010E',
   '22183',
   '23552',
   '22164',
   '23165',
   '90214Y',
   '21398',
   '20725',
   '22261',
   '21389',
   '22666',
   '22607',
   '72760B',
   '23640',
   '23233',
   '21675',
   '84907',
   '85188A',
   '84970s',
   '62086A',
   '85188B',
   '90124C',
   '37491A',
   '22897',
   '23567',
   '21187',
   '23317',
   '35265',
   '22884',
   '23286',
   '85131C',
   '21364',
   '22517',
   '21738',
   '82613A',
   '21191',
   '22377',
   '90177E',
   '84638',
   '23451',
   '21457',
   '84993B',
   '22849',

In [103]:
product_base["StockCode"] = (
    product_base["StockCode"]
    .astype(str)
    .str.strip()
)

In [104]:
product_base["related_product_count"] = (
    product_base["StockCode"]
    .map(lambda x: len(related_products.get(x, set())))
)

In [105]:
product_base.head()

,StockCode,total_quantity,avg_quantity_per_order,order_frequency,related_product_count
0,10002,860,12.112676,71,2067
1,10080,303,13.772727,22,908
2,10120,192,6.620690,29,1001
3,10123C,5,1.666667,3,85
4,10124A,16,3.200000,5,196

In [106]:
clustering_features = product_base[
    [
        "StockCode",
        "order_frequency",
        "total_quantity",
        "avg_quantity_per_order",
        "related_product_count"
    ]
].copy()

In [107]:
clustering_features.head()

,StockCode,order_frequency,total_quantity,avg_quantity_per_order,related_product_count
0,10002,71,860,12.112676,2067
1,10080,22,303,13.772727,908
2,10120,29,192,6.620690,1001
3,10123C,3,5,1.666667,85
4,10124A,5,16,3.200000,196

In [108]:
from sklearn.preprocessing import StandardScaler

features_for_clustering = [
    "order_frequency",
    "total_quantity",
    "avg_quantity_per_order",
    "related_product_count"
]

X = product_base[features_for_clustering].copy()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [109]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

product_base["cluster"] = kmeans.fit_predict(X_scaled)

In [110]:
print(product_base["cluster"].value_counts().sort_index())

cluster
0    2192
1    1551
2       1
3     178
Name: count, dtype: int64

In [111]:
cluster_summary = product_base.groupby("cluster")[
    features_for_clustering
].mean()

print(cluster_summary)

         order_frequency  total_quantity  avg_quantity_per_order  \
cluster
0             161.242245     1414.904653                8.246309
1              17.390071      173.529336                8.247929
2               1.000000    80995.000000            80995.000000
3             781.949438    11914.662921               17.931036

         related_product_count
cluster
0                  2573.554288
1                   827.516441
2                     0.000000
3                  3237.657303

In [134]:
cluster_names = {
    0: "Active/Regular Products",
    1: "Slow-Moving Products",
    2: "Bulk/Exceptional Products",
    3: "High-Volume Products"
}

In [135]:
product_base["cluster_name"] = (
    product_base["cluster"].map(cluster_names)
)

In [136]:
print(
    product_base["cluster_name"].value_counts()
)

cluster_name
Active/Regular Products      2192
Slow-Moving Products         1551
High-Volume Products          178
Bulk/Exceptional Products       1
Name: count, dtype: int64

In [137]:
zone_mapping = {
    "High-Volume Products": "Zone A",
    "Active/Regular Products": "Zone B",
    "Low-Movement Products": "Zone C",
    "Slow-Moving Products": "Zone D"
}

product_base["recommended_zone"] = (
    product_base["cluster_name"].map(zone_mapping)
)

In [138]:
product_base[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone"
    ]
].head(20)

   StockCode             cluster_name recommended_zone
0      10002  Active/Regular Products           Zone B
1      10080     Slow-Moving Products           Zone D
2      10120     Slow-Moving Products           Zone D
3     10123C     Slow-Moving Products           Zone D
4     10124A     Slow-Moving Products           Zone D
5     10124G     Slow-Moving Products           Zone D
6      10125  Active/Regular Products           Zone B
7      10133  Active/Regular Products           Zone B
8      10135  Active/Regular Products           Zone B
9      11001  Active/Regular Products           Zone B
10     15030     Slow-Moving Products           Zone D
11     15034  Active/Regular Products           Zone B
12     15036     High-Volume Products           Zone A
13     15039  Active/Regular Products           Zone B
14    15044A  Active/Regular Products           Zone B
15    15044B     Slow-Moving Products           Zone D
16    15044C  Active/Regular Products           Zone B
17    15044D  Active/Regular Products           Zone B
18   15056BL  Active/Regular Products           Zone B
19    15056N  Active/Regular Products           Zone B

In [139]:
zone_distance = {
    "Zone A": 10,
    "Zone B": 25,
    "Zone C": 40,
    "Zone D": 60
}

product_base["distance_from_packing"] = (
    product_base["recommended_zone"].map(zone_distance)
)

In [140]:
product_base[
    [
        "StockCode",
        "recommended_zone",
        "distance_from_packing"
    ]
].head(20)

   StockCode recommended_zone  distance_from_packing
0      10002           Zone B                   25.0
1      10080           Zone D                   60.0
2      10120           Zone D                   60.0
3     10123C           Zone D                   60.0
4     10124A           Zone D                   60.0
5     10124G           Zone D                   60.0
6      10125           Zone B                   25.0
7      10133           Zone B                   25.0
8      10135           Zone B                   25.0
9      11001           Zone B                   25.0
10     15030           Zone D                   60.0
11     15034           Zone B                   25.0
12     15036           Zone A                   10.0
13     15039           Zone B                   25.0
14    15044A           Zone B                   25.0
15    15044B           Zone D                   60.0
16    15044C           Zone B                   25.0
17    15044D           Zone B                   25.0
18   15056BL           Zone B                   25.0
19    15056N           Zone B                   25.0

In [141]:
product_base["picking_priority"] = (
    product_base["order_frequency"]
    * product_base["total_quantity"]
)

In [142]:
top_products = product_base.sort_values(
    "picking_priority",
    ascending=False
)

top_products[
    [
        "StockCode",
        "order_frequency",
        "total_quantity",
        "cluster_name",
        "recommended_zone",
        "picking_priority"
    ]
].head(20)

,StockCode,order_frequency,total_quantity,cluster_name,recommended_zone,picking_priority
3387,85099B,2089,48371,High-Volume Products,Zone A,101047019
3407,85123A,2198,37641,High-Volume Products,Zone A,82734918
1109,22197,1392,56898,High-Volume Products,Zone A,79202016
3194,84879,1455,36362,High-Volume Products,Zone A,52906710
439,21212,1320,36396,High-Volume Products,Zone A,48042720
2670,47566,1685,18283,High-Volume Products,Zone A,30806855
1942,23084,994,30739,High-Volume Products,Zone A,30554566
175,20725,1565,19432,High-Volume Products,Zone A,30411080
2909,84077,535,54951,High-Volume Products,Zone A,29398785
1310,22423,1988,13851,High-Volume Products,Zone A,27535788
1279,22386,1218,21448,High-Volume Products,Zone A,26123664
2056,23203,1231,20485,High-Volume Products,Zone A,25217035
1090,22178,1037,24275,High-Volume Products,Zone A,25173175
1006,22086,1160,19329,High-Volume Products,Zone A,22421640
1353,22469,1201,17963,High-Volume Products,Zone A,21573563
930,21977,869,24820,High-Volume Products,Zone A,21568580
2020,23166,247,78033,High-Volume Products,Zone A,19274151
1825,22961,1162,16396,High-Volume Products,Zone A,19052152
174,20724,1032,17761,High-Volume Products,Zone A,18329352
3234,84946,905,19209,High-Volume Products,Zone A,17384145

In [143]:
product_base["current_distance"] = 60

In [144]:
product_base["distance_saved"] = (
    product_base["current_distance"]
    - product_base["distance_from_packing"]
)

In [145]:
product_base[
    [
        "StockCode",
        "current_distance",
        "distance_from_packing",
        "distance_saved"
    ]
].head(20)

   StockCode  current_distance  distance_from_packing  distance_saved
0      10002                60                   25.0            35.0
1      10080                60                   60.0             0.0
2      10120                60                   60.0             0.0
3     10123C                60                   60.0             0.0
4     10124A                60                   60.0             0.0
5     10124G                60                   60.0             0.0
6      10125                60                   25.0            35.0
7      10133                60                   25.0            35.0
8      10135                60                   25.0            35.0
9      11001                60                   25.0            35.0
10     15030                60                   60.0             0.0
11     15034                60                   25.0            35.0
12     15036                60                   10.0            50.0
13     15039                60                   25.0            35.0
14    15044A                60                   25.0            35.0
15    15044B                60                   60.0             0.0
16    15044C                60                   25.0            35.0
17    15044D                60                   25.0            35.0
18   15056BL                60                   25.0            35.0
19    15056N                60                   25.0            35.0

In [146]:
total_current_distance = (
    product_base["current_distance"]
    * product_base["order_frequency"]
).sum()

In [147]:
total_recommended_distance = (
    product_base["distance_from_packing"]
    * product_base["order_frequency"]
).sum()

In [148]:
print(
    "Current estimated travel:",
    total_current_distance
)

print(
    "Recommended estimated travel:",
    total_recommended_distance
)

Current estimated travel: 31176180
Recommended estimated travel: 11846265.0

In [149]:
if total_current_distance > 0:

    travel_reduction = (
        (total_current_distance - total_recommended_distance)
        / total_current_distance
    ) * 100

else:
    travel_reduction = 0

print(
    f"Estimated travel reduction: {travel_reduction:.2f}%"
)

Estimated travel reduction: 62.00%

In [150]:
final_recommendations = product_base[
    [
        "StockCode",
        "order_frequency",
        "total_quantity",
        "avg_quantity_per_order",
        "related_product_count",
        "cluster_name",
        "recommended_zone",
        "distance_from_packing",
        "picking_priority",
        "current_distance",
        "distance_saved"
    ]
].copy()

In [151]:
final_recommendations = final_recommendations.sort_values(
    "picking_priority",
    ascending=False
)

In [152]:
final_recommendations.head(20)

,StockCode,order_frequency,total_quantity,avg_quantity_per_order,related_product_count,cluster_name,recommended_zone,distance_from_packing,picking_priority,current_distance,distance_saved
3387,85099B,2089,48371,22.935514,3513,High-Volume Products,Zone A,10.0,101047019,60,50.0
3407,85123A,2198,37641,16.707057,3562,High-Volume Products,Zone A,10.0,82734918,60,50.0
1109,22197,1392,56898,40.125529,3545,High-Volume Products,Zone A,10.0,79202016,60,50.0
3194,84879,1455,36362,24.635501,3351,High-Volume Products,Zone A,10.0,52906710,60,50.0
439,21212,1320,36396,26.920118,3438,High-Volume Products,Zone A,10.0,48042720,60,50.0
2670,47566,1685,18283,10.761036,3480,High-Volume Products,Zone A,10.0,30806855,60,50.0
1942,23084,994,30739,30.225172,3122,High-Volume Products,Zone A,10.0,30554566,60,50.0
175,20725,1565,19432,12.283186,3469,High-Volume Products,Zone A,10.0,30411080,60,50.0
2909,84077,535,54951,102.520522,3125,High-Volume Products,Zone A,10.0,29398785,60,50.0
1310,22423,1988,13851,6.901345,3537,High-Volume Products,Zone A,10.0,27535788,60,50.0
1279,22386,1218,21448,17.409091,3354,High-Volume Products,Zone A,10.0,26123664,60,50.0
2056,23203,1231,20485,16.493559,3110,High-Volume Products,Zone A,10.0,25217035,60,50.0
1090,22178,1037,24275,23.318924,3451,High-Volume Products,Zone A,10.0,25173175,60,50.0
1006,22086,1160,19329,16.325169,3372,High-Volume Products,Zone A,10.0,22421640,60,50.0
1353,22469,1201,17963,14.735849,3522,High-Volume Products,Zone A,10.0,21573563,60,50.0
930,21977,869,24820,28.204545,3415,High-Volume Products,Zone A,10.0,21568580,60,50.0
2020,23166,247,78033,312.132000,2784,High-Volume Products,Zone A,10.0,19274151,60,50.0
1825,22961,1162,16396,14.085911,3475,High-Volume Products,Zone A,10.0,19052152,60,50.0
174,20724,1032,17761,17.012452,3390,High-Volume Products,Zone A,10.0,18329352,60,50.0
3234,84946,905,19209,21.062500,3395,High-Volume Products,Zone A,10.0,17384145,60,50.0

In [153]:
final_recommendations.to_csv(
    "../data/processed/final_slot_recommendations.csv",
    index=False
)

In [154]:
final_recommendations[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone",
        "picking_priority",
        "distance_saved"
    ]
].head(10)

,StockCode,cluster_name,recommended_zone,picking_priority,distance_saved
3387,85099B,High-Volume Products,Zone A,101047019,50.0
3407,85123A,High-Volume Products,Zone A,82734918,50.0
1109,22197,High-Volume Products,Zone A,79202016,50.0
3194,84879,High-Volume Products,Zone A,52906710,50.0
439,21212,High-Volume Products,Zone A,48042720,50.0
2670,47566,High-Volume Products,Zone A,30806855,50.0
1942,23084,High-Volume Products,Zone A,30554566,50.0
175,20725,High-Volume Products,Zone A,30411080,50.0
2909,84077,High-Volume Products,Zone A,29398785,50.0
1310,22423,High-Volume Products,Zone A,27535788,50.0

In [155]:
cluster_summary = product_base.groupby("cluster")[
    [
        "order_frequency",
        "total_quantity",
        "avg_quantity_per_order",
        "related_product_count"
    ]
].mean()

print(cluster_summary)

         order_frequency  total_quantity  avg_quantity_per_order  \
cluster
0             161.242245     1414.904653                8.246309
1              17.390071      173.529336                8.247929
2               1.000000    80995.000000            80995.000000
3             781.949438    11914.662921               17.931036

         related_product_count
cluster
0                  2573.554288
1                   827.516441
2                     0.000000
3                  3237.657303