In [1]:
import pandas as pd

final_recommendations = pd.read_csv(
    "../data/processed/final_slot_recommendations.csv"
)

final_recommendations.head()

,StockCode,order_frequency,total_quantity,avg_quantity_per_order,related_product_count,cluster_name,recommended_zone,distance_from_packing,picking_priority,current_distance,distance_saved
0,85099B,2089,48371,22.935514,3513,High-Volume Products,Zone A,10.0,101047019,60,50.0
1,85123A,2198,37641,16.707057,3562,High-Volume Products,Zone A,10.0,82734918,60,50.0
2,22197,1392,56898,40.125529,3545,High-Volume Products,Zone A,10.0,79202016,60,50.0
3,84879,1455,36362,24.635501,3351,High-Volume Products,Zone A,10.0,52906710,60,50.0
4,21212,1320,36396,26.920118,3438,High-Volume Products,Zone A,10.0,48042720,60,50.0

In [2]:
top_products = final_recommendations.sort_values(
    "picking_priority",
    ascending=False
)

top_products[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone",
        "picking_priority",
        "distance_saved"
    ]
].head(20)

,StockCode,cluster_name,recommended_zone,picking_priority,distance_saved
0,85099B,High-Volume Products,Zone A,101047019,50.0
1,85123A,High-Volume Products,Zone A,82734918,50.0
2,22197,High-Volume Products,Zone A,79202016,50.0
3,84879,High-Volume Products,Zone A,52906710,50.0
4,21212,High-Volume Products,Zone A,48042720,50.0
5,47566,High-Volume Products,Zone A,30806855,50.0
6,23084,High-Volume Products,Zone A,30554566,50.0
7,20725,High-Volume Products,Zone A,30411080,50.0
8,84077,High-Volume Products,Zone A,29398785,50.0
9,22423,High-Volume Products,Zone A,27535788,50.0
10,22386,High-Volume Products,Zone A,26123664,50.0
11,23203,High-Volume Products,Zone A,25217035,50.0
12,22178,High-Volume Products,Zone A,25173175,50.0
13,22086,High-Volume Products,Zone A,22421640,50.0
14,22469,High-Volume Products,Zone A,21573563,50.0
15,21977,High-Volume Products,Zone A,21568580,50.0
16,23166,High-Volume Products,Zone A,19274151,50.0
17,22961,High-Volume Products,Zone A,19052152,50.0
18,20724,High-Volume Products,Zone A,18329352,50.0
19,84946,High-Volume Products,Zone A,17384145,50.0

In [3]:
zone_summary = final_recommendations.groupby(
    "recommended_zone"
).agg(
    product_count=("StockCode", "count"),
    avg_priority=("picking_priority", "mean"),
    avg_distance_saved=("distance_saved", "mean")
)

zone_summary

                  product_count  avg_priority  avg_distance_saved
recommended_zone
Zone A                      178  1.014923e+07                50.0
Zone B                     2192  3.471868e+05                35.0
Zone D                     1551  7.273714e+03                 0.0

In [4]:
cluster_summary_final = final_recommendations.groupby(
    "cluster_name"
).agg(
    product_count=("StockCode", "count"),
    avg_order_frequency=("order_frequency", "mean"),
    avg_total_quantity=("total_quantity", "mean"),
    avg_distance_saved=("distance_saved", "mean")
)

cluster_summary_final

,product_count,avg_order_frequency,avg_total_quantity,avg_distance_saved
cluster_name,,,,
Active/Regular Products,2192,161.242245,1414.904653,35.0
Bulk/Exceptional Products,1,1.000000,80995.000000,NaN
High-Volume Products,178,781.949438,11914.662921,50.0
Slow-Moving Products,1551,17.390071,173.529336,0.0

In [5]:
highest_savings = final_recommendations.sort_values(
    "distance_saved",
    ascending=False
)

highest_savings[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone",
        "distance_saved"
    ]
].head(20)

   StockCode          cluster_name recommended_zone  distance_saved
47     22720  High-Volume Products           Zone A            50.0
15     21977  High-Volume Products           Zone A            50.0
31     20728  High-Volume Products           Zone A            50.0
16     23166  High-Volume Products           Zone A            50.0
17     22961  High-Volume Products           Zone A            50.0
18     20724  High-Volume Products           Zone A            50.0
19     84946  High-Volume Products           Zone A            50.0
20     21931  High-Volume Products           Zone A            50.0
21     22383  High-Volume Products           Zone A            50.0
22     22355  High-Volume Products           Zone A            50.0
23     20727  High-Volume Products           Zone A            50.0
24     84991  High-Volume Products           Zone A            50.0
25     22411  High-Volume Products           Zone A            50.0
26     23199  High-Volume Products           Zone A            50.0
27     21915  High-Volume Products           Zone A            50.0
28     23209  High-Volume Products           Zone A            50.0
29    85099F  High-Volume Products           Zone A            50.0
30     22993  High-Volume Products           Zone A            50.0
63     84978  High-Volume Products           Zone A            50.0
32     21790  High-Volume Products           Zone A            50.0

In [6]:
final_recommendations["business_recommendation"] = (
    "Place in " +
    final_recommendations["recommended_zone"] +
    " based on product movement and picking priority."
)

In [9]:
final_recommendations[
    [
        "StockCode",
        "cluster_name",
        "recommended_zone",
        "picking_priority",
        "business_recommendation"
    ]
].head()

,StockCode,cluster_name,recommended_zone,picking_priority,business_recommendation
0,85099B,High-Volume Products,Zone A,101047019,Place in Zone A based on product movement and ...
1,85123A,High-Volume Products,Zone A,82734918,Place in Zone A based on product movement and ...
2,22197,High-Volume Products,Zone A,79202016,Place in Zone A based on product movement and ...
3,84879,High-Volume Products,Zone A,52906710,Place in Zone A based on product movement and ...
4,21212,High-Volume Products,Zone A,48042720,Place in Zone A based on product movement and ...

In [10]:
final_recommendations.to_csv(
    "../data/processed/business_slotting_recommendations.csv",
    index=False
)